### ISSUE TITLE
Syntactic judgement that reflects cumulativity

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/McLTT#100]
Suppose the case of `rec M return idOfType4 Type@3 | zero -> Type@0 | succ -> Type@1`.
To infer `Type@3` or check against `Type@j` (where `j >= 3`), we need decidable checking that `idOfType4 Type@3` has some relation with `Type@1` (the minimum universe of `Type@0`) (and also with `Type@2` for `Type@1`).
This relation is not conversion; clearly their normal forms, `Type@3` and `Type@1`, are not convertible.

One way to deal with this is, after normalization (by evaluation), instead of checking syntactic equality between the normal forms of the inferred type and given type, we can check that the (normal form of) given type is obtained by applying cumulativity on the inferred type. Yet, we have a problem. To what is this check actually realized? We do not have a syntactic judgement that describes the notion of "conversion, but with directed cumulativity". In other words, we do not have a good return type for a function like
https://github.com/Beluga-lang/McLTT/blob/6f4fb0d35eb96fc3e6df92c97392d68744d93783/theories/Extraction/TypeCheck.v#L26-L35
because we do not have something like `{{ G ⊢ M ≈ M' : A }}` for "conversion, but with directed cumulativity".

**Comment by Ailrun** [comment]
Not just for `exp` type, but we need a good judgement for `nf` (and thus `ne`), so that we can replace `nf_eq_dec`.

**Comment by HuStmpHrrr** [comment]
In fact, after thinking a bit, I think what I said was wrong. the typechecker should really just be checking types. There is always a type to check against to. otherwise, due to lack of subtyping, we might not be able to arrive at the right decision. for one example, consider:

```
fun (x : Nat). Nat : Pi(x : Nat). Type@1
```
the problem here is we cannot infer the level of `Nat` in the body correctly without looking at the type itself. 

so I think we need two algorithms:

1. `check G t T : bool`  decides whether `t` has type `T`.
2. `is_type G T : bool` decides whether `T` has type `Type@i` for some `i`. 

I feel that these two functions are defined mutually. we probably don't need the judgments you added to your PR.

**Comment by HuStmpHrrr** [comment]
or maybe not. we need them to handle the variable case. let me write down some rules.

**Comment by HuStmpHrrr** [comment]
Oh, I guess we need an inference direction... hmm...

**Comment by HuStmpHrrr** [comment]
![IMG20240605231701](https://github.com/Beluga-lang/McLTT/assets/6101711/145edb77-0be0-4a09-b5b3-8f51ba27f2ab)

these are the rules that I come up with. notice how annoying the lambda case is, because of cumulativity. another annoying thing is that we need to prove it equivalent to the declarative typing rules.

**Comment by HuStmpHrrr** [comment]
https://arxiv.org/pdf/2310.06376

section 6.3.3

> There is an important caveat to algorithmic typing as defined in AlgorithmicTyping: it is not, in general, equivalent to declarative typing.

Yikes.

**Comment by Ailrun** [comment]
> https://arxiv.org/pdf/2310.06376
>
> section 6.3.3
>
> > There is an important caveat to algorithmic typing as defined in AlgorithmicTyping: it is not, in general, equivalent to declarative typing.
>
> Yikes.

I don't think that's a serious problem. If I understand what they say correctly, it's just that the algorithmic typing judgement alone is not equivalent to the declarative one, but with some additional ambient conditions, it is. Like, instead of having `G |-alg M : A <-> G |- M : A`, we have something like `(|-alg G /\ G |-alg M : A) <-> G |- M : A`, which should be fine IMO.

**Comment by Ailrun** [comment]
Yeah, they indeed proved
https://coqhott.github.io/logrel-coq/coqdoc/LogRel.BundledAlgorithmicTyping.html#bn_typing_sound and https://coqhott.github.io/logrel-coq/coqdoc/LogRel.AlgorithmicTypingProperties.html#algo_typing_complete
so the "bundled" version (the one with relevant conditions on context and so on) is equivalent to the declarative one.

**Comment by HuStmpHrrr** [comment]
what can we take from their stuff?

**Comment by Ailrun** [comment]
IDK, the coq-partialfun thing looks interesting, but I'm not sure how much we can take as their judgements are all in `Type` (which may or may not have impact)
